server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FranciscoCY/B_35_Proyect.git
          searchPaths: Config-Data
          username: FranciscoCY
          password: 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

  security:
    user:
      name: root
      password: s3cr3t